# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/accelerator/accelerator.srcs/sources_1/bd/system/ip/system_matmul_accel_0_0/system_matmul_accel_0_0.xci
# IP: The module: 'system_matmul_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/accelerator/accelerator.gen/sources_1/bd/system/ip/system_matmul_accel_0_0/constraints/matmul_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_matmul_accel_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/accelerator/accelerator.srcs/sources_1/bd/system/ip/system_matmul_accel_0_0/system_matmul_accel_0_0.xci
# IP: The module: 'system_matmul_accel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/accelerator/accelerator.gen/sources_1/bd/system/ip/system_matmul_accel_0_0/constraints/matmul_accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_matmul_accel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
